version: 2.1

jobs:
  build:
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker image build -t manojm003/ros:jazzy -f Dockerfile .
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "circleci-project-setup" ]; then
              echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
              docker image ls
              docker push theasp/novnc:latest
            fi

workflows:
  builder:
    jobs:
      - build
