version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build_and_push:
    docker:
      - image: docker
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker Image
          command: |
            cd .devcontainer
            docker-compose build
      - run:
          name: Login to Docker Hub
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            cd .devcontainer
            docker-compose push

workflows:
  builder:
    jobs:
      - build_and_push
